[package]
name = "openjoc-emdf"
version.workspace = true
description = "Bounded EMDF parsing and explicit JOC profile validation"
edition.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
openjoc-bitio = { version = "0.6.0", path = "../openjoc-bitio" }

[lints]
workspace = true
