[package]
name = "openjoc-cli"
version = "0.1.0"
description = "Open-source JOC decoder"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "openjoc"
path = "src/main.rs"

[dependencies]
openjoc-eac3 = { path = "../openjoc-eac3" }
openjoc-oamd = { path = "../openjoc-oamd" }
openjoc-scene = { path = "../openjoc-scene" }
openjoc-wave = { path = "../openjoc-wave" }
terminal_size = "0.4"

[dev-dependencies]
openjoc-wave = { path = "../openjoc-wave" }

[lints]
workspace = true
